### ISSUE TITLE
RedirectHandler attempts to follow redirects on 304 

### ISSUE THREAD

**Issue by dmuino** [Netflix/spectator#130]
Currently it's doing:

```java
    if (code > 300 && code <= 307) {
      // attempt redirect
```

But a 'Not Modified' response is 304, and will cause a null pointer exception.

```
java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        at com.netflix.iep.http.RedirectHandler.call(RedirectHandler.java:54)
        at com.netflix.iep.http.RedirectHandler.call(RedirectHandler.java:30)
        at iep.rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
        at iep.rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
        at iep.rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
        at iep.rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
        at iep.rx.internal.operators.OperatorFinally$1.onNext(OperatorFinally.java:45)
        at iep.rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:67)
        at iep.io.reactivex.netty.protocol.http.client.RedirectOperator$RedirectSubscriber.onNext(RedirectOperator.java:256)
        at iep.io.reactivex.netty.protocol.http.client.RedirectOperator$RedirectSubscriber.onNext(RedirectOperator.java:205)
        at iep.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
        at iep.rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
        at iep.rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:84)
        at iep.rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
        at iep.rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
        at iep.rx.observers.SerializedObserver.onNext(SerializedObserver.java:159)
        at iep.rx.subjects.SerializedSubject.onNext(SerializedSubject.java:64)
        at iep.io.reactivex.netty.pipeline.ObservableAdapter.channelRead(ObservableAdapter.java:40)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at iep.io.reactivex.netty.protocol.http.client.ClientRequestResponseConverter.channelRead(ClientRequestResponseConverter.java:130)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at iep.io.reactivex.netty.metrics.BytesInspector.channelRead(BytesInspector.java:59)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: iep.rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: iep.io.reactivex.netty.protocol.http.client.HttpClientResponse.class
        at iep.rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:98)
        at iep.rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
```

**Comment by dmuino** [comment]
Wrong project. It should be iep/
