### ISSUE TITLE
reflective access to default methods is broken on jdk9

### ISSUE THREAD

**Issue by brharrington** [Netflix/spectator#425]
When running spectator on jdk9 we get errors like:

```
Caused by: java.lang.IllegalAccessException: access to public member failed: com.netflix.spectator.api.RegistryConfig.gaugePollingFrequency()Duration/invokeSpecial, from com.netflix.spectator.api.RegistryConfig/2 (unnamed module @36d4b5c)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:914)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2193)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2133)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2282)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2276)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1800)
	at com.netflix.spectator.impl.Config.lambda$createProxy$3(Config.java:131)
	... 50 more
```

This is coming from the reflection code used to try and call default methods on the config interfaces from proxy objects. See also discussion on jdk mailing list:

http://mail.openjdk.java.net/pipermail/mlvm-dev/2016-June/006646.html

**Comment by brharrington** [comment]
A possible work-around:

http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-January/010741.html
