### ISSUE TITLE
test failure for clean checkout

### ISSUE THREAD

**Issue by brharrington** [Netflix/spectator#777]
There is a test failure for a clean clone on `spectator-nflx` for `AutoPluginTest`. The error is:

```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: com/netflix/spectator/impl/Cache
  at com.netflix.spectator.atlas.AtlasRegistry.<init>(AtlasRegistry.java:116)
  at com.netflix.spectator.atlas.AtlasRegistry.class(AtlasRegistry.java:110)
  while locating com.netflix.spectator.atlas.AtlasRegistry
  at com.netflix.spectator.nflx.SpectatorModule.configure(SpectatorModule.java:91) (via modules: com.netflix.spectator.nflx.governator.AutoPlugin -> com.netflix.spectator.nflx.SpectatorModule)
  while locating com.netflix.spectator.api.Registry annotated with @com.google.inject.multibindings.OptionalBinder$Default
Caused by: java.lang.NoClassDefFoundError: com/netflix/spectator/impl/Cache
	at com.netflix.spectator.atlas.impl.QueryIndex.<init>(QueryIndex.java:89)
	at com.netflix.spectator.atlas.impl.QueryIndex.newInstance(QueryIndex.java:41)
	at com.netflix.spectator.atlas.impl.Evaluator.<init>(Evaluator.java:64)
```

The problem is that gradle is resolving it to an older dependency. If the tags are present in the local repo, then the snapshot will have a newer version and the local project will win and get used. Otherwise an older version will get used that maybe incompatible:

```
> Task :spectator-nflx:dependencyInsight
com.netflix.spectator:spectator-api:0.88.0
   variant "runtime" [
      org.gradle.status          = release (not requested)
      org.gradle.usage           = java-runtime (not requested)
      org.gradle.libraryelements = jar (not requested)
      org.gradle.category        = library (not requested)
   ]
   Selection reasons:
      - By conflict resolution : between versions 0.1.0-SNAPSHOT and 0.88.0

project :spectator-api -> com.netflix.spectator:spectator-api:0.88.0
+--- project :spectator-nflx-plugin
|    \--- runtime
+--- project :spectator-ext-gc
|    \--- project :spectator-nflx-plugin (*)
+--- project :spectator-ext-jvm
|    \--- project :spectator-nflx-plugin (*)
+--- project :spectator-ext-ipc
|    \--- project :spectator-reg-atlas
|         \--- project :spectator-nflx-plugin (*)
\--- project :spectator-reg-atlas (*)

com.netflix.spectator:spectator-api:0.88.0
\--- com.netflix.servo:servo-core:0.12.28
     \--- project :spectator-nflx-plugin (requested com.netflix.servo:servo-core)
          \--- runtime

(*) - dependencies omitted (listed previously)
```

**Comment by brharrington** [comment]
The problem is the git tags used for the version were missing. For now user should be sure to do a fetch so that tags are available. Not sure of a good workaround right now, will revisit if it becomes a bigger issue.
